
financialrecommendsystem:
  name: FinancialRecommend
  profile: D:\Financial-Recommendation-Project\FinancialRecommendSystem\upload
server:
  port: 8888
  servlet:
    context-path: /FinancialRecommend
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/financial_recommend?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/
mybatis-plus:
  mapper-locations: classpath:/com/viego/financialrecommendsystem/mapper/*.xml
  type-aliases-package: com.viego.financialrecommendsystem.entity
  configuration:
    auto-fill: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
